/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignAccountingRouteImport } from './routes/design/accounting'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppSalesRouteImport } from './routes/app/sales'
import { Route as AppReturnsRouteImport } from './routes/app/returns'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppPurchasesRouteImport } from './routes/app/purchases'
import { Route as AppPurchaseOrdersRouteImport } from './routes/app/purchase-orders'
import { Route as AppPurchaseGrnsRouteImport } from './routes/app/purchase-grns'
import { Route as AppPaymentsRouteImport } from './routes/app/payments'
import { Route as AppOcrRouteImport } from './routes/app/ocr'
import { Route as AppInventoryRouteImport } from './routes/app/inventory'
import { Route as AppImportsRouteImport } from './routes/app/imports'
import { Route as AppExpensesRouteImport } from './routes/app/expenses'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppBankReconciliationRouteImport } from './routes/app/bank-reconciliation'
import { Route as AppSalesIndexRouteImport } from './routes/app/sales/index'
import { Route as AppPurchasesIndexRouteImport } from './routes/app/purchases/index'
import { Route as DesignAccountingSidebarRouteImport } from './routes/design/accounting/sidebar'
import { Route as AppSalesNewRouteImport } from './routes/app/sales/new'
import { Route as AppSalesDocumentsRouteImport } from './routes/app/sales/documents'
import { Route as AppPurchasesNewRouteImport } from './routes/app/purchases/new'
import { Route as AppMastersPartiesRouteImport } from './routes/app/masters/parties'
import { Route as AppMastersItemsRouteImport } from './routes/app/masters/items'
import { Route as AppMastersGodownsRouteImport } from './routes/app/masters/godowns'
import { Route as AppMastersCompanyProfileRouteImport } from './routes/app/masters/company-profile'
import { Route as AppMastersCompaniesRouteImport } from './routes/app/masters/companies'
import { Route as AppMastersChartOfAccountsRouteImport } from './routes/app/masters/chart-of-accounts'
import { Route as AppAccountingJournalRouteImport } from './routes/app/accounting/journal'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSalesInvoiceIdPrintRouteImport } from './routes/app/sales/$invoiceId.print'
import { Route as AppPurchasesBillIdPrintRouteImport } from './routes/app/purchases/$billId.print'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignAccountingRoute = DesignAccountingRouteImport.update({
  id: '/design/accounting',
  path: '/design/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsRoute = AppReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseGrnsRoute = AppPurchaseGrnsRouteImport.update({
  id: '/purchase-grns',
  path: '/purchase-grns',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppOcrRoute = AppOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppImportsRoute = AppImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBankReconciliationRoute = AppBankReconciliationRouteImport.update({
  id: '/bank-reconciliation',
  path: '/bank-reconciliation',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppPurchasesIndexRoute = AppPurchasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPurchasesRoute,
} as any)
const DesignAccountingSidebarRoute = DesignAccountingSidebarRouteImport.update({
  id: '/sidebar',
  path: '/sidebar',
  getParentRoute: () => DesignAccountingRoute,
} as any)
const AppSalesNewRoute = AppSalesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesDocumentsRoute = AppSalesDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppPurchasesNewRoute = AppPurchasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPurchasesRoute,
} as any)
const AppMastersPartiesRoute = AppMastersPartiesRouteImport.update({
  id: '/masters/parties',
  path: '/masters/parties',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersItemsRoute = AppMastersItemsRouteImport.update({
  id: '/masters/items',
  path: '/masters/items',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersGodownsRoute = AppMastersGodownsRouteImport.update({
  id: '/masters/godowns',
  path: '/masters/godowns',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersCompanyProfileRoute =
  AppMastersCompanyProfileRouteImport.update({
    id: '/masters/company-profile',
    path: '/masters/company-profile',
    getParentRoute: () => AppRoute,
  } as any)
const AppMastersCompaniesRoute = AppMastersCompaniesRouteImport.update({
  id: '/masters/companies',
  path: '/masters/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersChartOfAccountsRoute =
  AppMastersChartOfAccountsRouteImport.update({
    id: '/masters/chart-of-accounts',
    path: '/masters/chart-of-accounts',
    getParentRoute: () => AppRoute,
  } as any)
const AppAccountingJournalRoute = AppAccountingJournalRouteImport.update({
  id: '/accounting/journal',
  path: '/accounting/journal',
  getParentRoute: () => AppRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSalesInvoiceIdPrintRoute = AppSalesInvoiceIdPrintRouteImport.update({
  id: '/$invoiceId/print',
  path: '/$invoiceId/print',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppPurchasesBillIdPrintRoute = AppPurchasesBillIdPrintRouteImport.update({
  id: '/$billId/print',
  path: '/$billId/print',
  getParentRoute: () => AppPurchasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/bank-reconciliation': typeof AppBankReconciliationRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/imports': typeof AppImportsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/ocr': typeof AppOcrRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/purchase-grns': typeof AppPurchaseGrnsRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/purchases': typeof AppPurchasesRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/returns': typeof AppReturnsRoute
  '/app/sales': typeof AppSalesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/design/accounting': typeof DesignAccountingRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/accounting/journal': typeof AppAccountingJournalRoute
  '/app/masters/chart-of-accounts': typeof AppMastersChartOfAccountsRoute
  '/app/masters/companies': typeof AppMastersCompaniesRoute
  '/app/masters/company-profile': typeof AppMastersCompanyProfileRoute
  '/app/masters/godowns': typeof AppMastersGodownsRoute
  '/app/masters/items': typeof AppMastersItemsRoute
  '/app/masters/parties': typeof AppMastersPartiesRoute
  '/app/purchases/new': typeof AppPurchasesNewRoute
  '/app/sales/documents': typeof AppSalesDocumentsRoute
  '/app/sales/new': typeof AppSalesNewRoute
  '/design/accounting/sidebar': typeof DesignAccountingSidebarRoute
  '/app/purchases/': typeof AppPurchasesIndexRoute
  '/app/sales/': typeof AppSalesIndexRoute
  '/app/purchases/$billId/print': typeof AppPurchasesBillIdPrintRoute
  '/app/sales/$invoiceId/print': typeof AppSalesInvoiceIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/bank-reconciliation': typeof AppBankReconciliationRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/imports': typeof AppImportsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/ocr': typeof AppOcrRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/purchase-grns': typeof AppPurchaseGrnsRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/returns': typeof AppReturnsRoute
  '/app/settings': typeof AppSettingsRoute
  '/design/accounting': typeof DesignAccountingRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/accounting/journal': typeof AppAccountingJournalRoute
  '/app/masters/chart-of-accounts': typeof AppMastersChartOfAccountsRoute
  '/app/masters/companies': typeof AppMastersCompaniesRoute
  '/app/masters/company-profile': typeof AppMastersCompanyProfileRoute
  '/app/masters/godowns': typeof AppMastersGodownsRoute
  '/app/masters/items': typeof AppMastersItemsRoute
  '/app/masters/parties': typeof AppMastersPartiesRoute
  '/app/purchases/new': typeof AppPurchasesNewRoute
  '/app/sales/documents': typeof AppSalesDocumentsRoute
  '/app/sales/new': typeof AppSalesNewRoute
  '/design/accounting/sidebar': typeof DesignAccountingSidebarRoute
  '/app/purchases': typeof AppPurchasesIndexRoute
  '/app/sales': typeof AppSalesIndexRoute
  '/app/purchases/$billId/print': typeof AppPurchasesBillIdPrintRoute
  '/app/sales/$invoiceId/print': typeof AppSalesInvoiceIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/bank-reconciliation': typeof AppBankReconciliationRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/imports': typeof AppImportsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/ocr': typeof AppOcrRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/purchase-grns': typeof AppPurchaseGrnsRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/purchases': typeof AppPurchasesRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/returns': typeof AppReturnsRoute
  '/app/sales': typeof AppSalesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/design/accounting': typeof DesignAccountingRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/accounting/journal': typeof AppAccountingJournalRoute
  '/app/masters/chart-of-accounts': typeof AppMastersChartOfAccountsRoute
  '/app/masters/companies': typeof AppMastersCompaniesRoute
  '/app/masters/company-profile': typeof AppMastersCompanyProfileRoute
  '/app/masters/godowns': typeof AppMastersGodownsRoute
  '/app/masters/items': typeof AppMastersItemsRoute
  '/app/masters/parties': typeof AppMastersPartiesRoute
  '/app/purchases/new': typeof AppPurchasesNewRoute
  '/app/sales/documents': typeof AppSalesDocumentsRoute
  '/app/sales/new': typeof AppSalesNewRoute
  '/design/accounting/sidebar': typeof DesignAccountingSidebarRoute
  '/app/purchases/': typeof AppPurchasesIndexRoute
  '/app/sales/': typeof AppSalesIndexRoute
  '/app/purchases/$billId/print': typeof AppPurchasesBillIdPrintRoute
  '/app/sales/$invoiceId/print': typeof AppSalesInvoiceIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/app/bank-reconciliation'
    | '/app/dashboard'
    | '/app/expenses'
    | '/app/imports'
    | '/app/inventory'
    | '/app/ocr'
    | '/app/payments'
    | '/app/purchase-grns'
    | '/app/purchase-orders'
    | '/app/purchases'
    | '/app/reports'
    | '/app/returns'
    | '/app/sales'
    | '/app/settings'
    | '/design/accounting'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/app/accounting/journal'
    | '/app/masters/chart-of-accounts'
    | '/app/masters/companies'
    | '/app/masters/company-profile'
    | '/app/masters/godowns'
    | '/app/masters/items'
    | '/app/masters/parties'
    | '/app/purchases/new'
    | '/app/sales/documents'
    | '/app/sales/new'
    | '/design/accounting/sidebar'
    | '/app/purchases/'
    | '/app/sales/'
    | '/app/purchases/$billId/print'
    | '/app/sales/$invoiceId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/app/bank-reconciliation'
    | '/app/dashboard'
    | '/app/expenses'
    | '/app/imports'
    | '/app/inventory'
    | '/app/ocr'
    | '/app/payments'
    | '/app/purchase-grns'
    | '/app/purchase-orders'
    | '/app/reports'
    | '/app/returns'
    | '/app/settings'
    | '/design/accounting'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/app/accounting/journal'
    | '/app/masters/chart-of-accounts'
    | '/app/masters/companies'
    | '/app/masters/company-profile'
    | '/app/masters/godowns'
    | '/app/masters/items'
    | '/app/masters/parties'
    | '/app/purchases/new'
    | '/app/sales/documents'
    | '/app/sales/new'
    | '/design/accounting/sidebar'
    | '/app/purchases'
    | '/app/sales'
    | '/app/purchases/$billId/print'
    | '/app/sales/$invoiceId/print'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/app/bank-reconciliation'
    | '/app/dashboard'
    | '/app/expenses'
    | '/app/imports'
    | '/app/inventory'
    | '/app/ocr'
    | '/app/payments'
    | '/app/purchase-grns'
    | '/app/purchase-orders'
    | '/app/purchases'
    | '/app/reports'
    | '/app/returns'
    | '/app/sales'
    | '/app/settings'
    | '/design/accounting'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/app/accounting/journal'
    | '/app/masters/chart-of-accounts'
    | '/app/masters/companies'
    | '/app/masters/company-profile'
    | '/app/masters/godowns'
    | '/app/masters/items'
    | '/app/masters/parties'
    | '/app/purchases/new'
    | '/app/sales/documents'
    | '/app/sales/new'
    | '/design/accounting/sidebar'
    | '/app/purchases/'
    | '/app/sales/'
    | '/app/purchases/$billId/print'
    | '/app/sales/$invoiceId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  DesignAccountingRoute: typeof DesignAccountingRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/accounting': {
      id: '/design/accounting'
      path: '/design/accounting'
      fullPath: '/design/accounting'
      preLoaderRoute: typeof DesignAccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales': {
      id: '/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/returns': {
      id: '/app/returns'
      path: '/returns'
      fullPath: '/app/returns'
      preLoaderRoute: typeof AppReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchases': {
      id: '/app/purchases'
      path: '/purchases'
      fullPath: '/app/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-orders': {
      id: '/app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-grns': {
      id: '/app/purchase-grns'
      path: '/purchase-grns'
      fullPath: '/app/purchase-grns'
      preLoaderRoute: typeof AppPurchaseGrnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ocr': {
      id: '/app/ocr'
      path: '/ocr'
      fullPath: '/app/ocr'
      preLoaderRoute: typeof AppOcrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/imports': {
      id: '/app/imports'
      path: '/imports'
      fullPath: '/app/imports'
      preLoaderRoute: typeof AppImportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bank-reconciliation': {
      id: '/app/bank-reconciliation'
      path: '/bank-reconciliation'
      fullPath: '/app/bank-reconciliation'
      preLoaderRoute: typeof AppBankReconciliationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales/': {
      id: '/app/sales/'
      path: '/'
      fullPath: '/app/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/app/purchases/': {
      id: '/app/purchases/'
      path: '/'
      fullPath: '/app/purchases/'
      preLoaderRoute: typeof AppPurchasesIndexRouteImport
      parentRoute: typeof AppPurchasesRoute
    }
    '/design/accounting/sidebar': {
      id: '/design/accounting/sidebar'
      path: '/sidebar'
      fullPath: '/design/accounting/sidebar'
      preLoaderRoute: typeof DesignAccountingSidebarRouteImport
      parentRoute: typeof DesignAccountingRoute
    }
    '/app/sales/new': {
      id: '/app/sales/new'
      path: '/new'
      fullPath: '/app/sales/new'
      preLoaderRoute: typeof AppSalesNewRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/app/sales/documents': {
      id: '/app/sales/documents'
      path: '/documents'
      fullPath: '/app/sales/documents'
      preLoaderRoute: typeof AppSalesDocumentsRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/app/purchases/new': {
      id: '/app/purchases/new'
      path: '/new'
      fullPath: '/app/purchases/new'
      preLoaderRoute: typeof AppPurchasesNewRouteImport
      parentRoute: typeof AppPurchasesRoute
    }
    '/app/masters/parties': {
      id: '/app/masters/parties'
      path: '/masters/parties'
      fullPath: '/app/masters/parties'
      preLoaderRoute: typeof AppMastersPartiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/masters/items': {
      id: '/app/masters/items'
      path: '/masters/items'
      fullPath: '/app/masters/items'
      preLoaderRoute: typeof AppMastersItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/masters/godowns': {
      id: '/app/masters/godowns'
      path: '/masters/godowns'
      fullPath: '/app/masters/godowns'
      preLoaderRoute: typeof AppMastersGodownsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/masters/company-profile': {
      id: '/app/masters/company-profile'
      path: '/masters/company-profile'
      fullPath: '/app/masters/company-profile'
      preLoaderRoute: typeof AppMastersCompanyProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/masters/companies': {
      id: '/app/masters/companies'
      path: '/masters/companies'
      fullPath: '/app/masters/companies'
      preLoaderRoute: typeof AppMastersCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/masters/chart-of-accounts': {
      id: '/app/masters/chart-of-accounts'
      path: '/masters/chart-of-accounts'
      fullPath: '/app/masters/chart-of-accounts'
      preLoaderRoute: typeof AppMastersChartOfAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounting/journal': {
      id: '/app/accounting/journal'
      path: '/accounting/journal'
      fullPath: '/app/accounting/journal'
      preLoaderRoute: typeof AppAccountingJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sales/$invoiceId/print': {
      id: '/app/sales/$invoiceId/print'
      path: '/$invoiceId/print'
      fullPath: '/app/sales/$invoiceId/print'
      preLoaderRoute: typeof AppSalesInvoiceIdPrintRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/app/purchases/$billId/print': {
      id: '/app/purchases/$billId/print'
      path: '/$billId/print'
      fullPath: '/app/purchases/$billId/print'
      preLoaderRoute: typeof AppPurchasesBillIdPrintRouteImport
      parentRoute: typeof AppPurchasesRoute
    }
  }
}

interface AppPurchasesRouteChildren {
  AppPurchasesNewRoute: typeof AppPurchasesNewRoute
  AppPurchasesIndexRoute: typeof AppPurchasesIndexRoute
  AppPurchasesBillIdPrintRoute: typeof AppPurchasesBillIdPrintRoute
}

const AppPurchasesRouteChildren: AppPurchasesRouteChildren = {
  AppPurchasesNewRoute: AppPurchasesNewRoute,
  AppPurchasesIndexRoute: AppPurchasesIndexRoute,
  AppPurchasesBillIdPrintRoute: AppPurchasesBillIdPrintRoute,
}

const AppPurchasesRouteWithChildren = AppPurchasesRoute._addFileChildren(
  AppPurchasesRouteChildren,
)

interface AppSalesRouteChildren {
  AppSalesDocumentsRoute: typeof AppSalesDocumentsRoute
  AppSalesNewRoute: typeof AppSalesNewRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppSalesInvoiceIdPrintRoute: typeof AppSalesInvoiceIdPrintRoute
}

const AppSalesRouteChildren: AppSalesRouteChildren = {
  AppSalesDocumentsRoute: AppSalesDocumentsRoute,
  AppSalesNewRoute: AppSalesNewRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppSalesInvoiceIdPrintRoute: AppSalesInvoiceIdPrintRoute,
}

const AppSalesRouteWithChildren = AppSalesRoute._addFileChildren(
  AppSalesRouteChildren,
)

interface AppRouteChildren {
  AppBankReconciliationRoute: typeof AppBankReconciliationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppImportsRoute: typeof AppImportsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppOcrRoute: typeof AppOcrRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPurchaseGrnsRoute: typeof AppPurchaseGrnsRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppPurchasesRoute: typeof AppPurchasesRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppReturnsRoute: typeof AppReturnsRoute
  AppSalesRoute: typeof AppSalesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppAccountingJournalRoute: typeof AppAccountingJournalRoute
  AppMastersChartOfAccountsRoute: typeof AppMastersChartOfAccountsRoute
  AppMastersCompaniesRoute: typeof AppMastersCompaniesRoute
  AppMastersCompanyProfileRoute: typeof AppMastersCompanyProfileRoute
  AppMastersGodownsRoute: typeof AppMastersGodownsRoute
  AppMastersItemsRoute: typeof AppMastersItemsRoute
  AppMastersPartiesRoute: typeof AppMastersPartiesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBankReconciliationRoute: AppBankReconciliationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppImportsRoute: AppImportsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppOcrRoute: AppOcrRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPurchaseGrnsRoute: AppPurchaseGrnsRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppPurchasesRoute: AppPurchasesRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppReturnsRoute: AppReturnsRoute,
  AppSalesRoute: AppSalesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppAccountingJournalRoute: AppAccountingJournalRoute,
  AppMastersChartOfAccountsRoute: AppMastersChartOfAccountsRoute,
  AppMastersCompaniesRoute: AppMastersCompaniesRoute,
  AppMastersCompanyProfileRoute: AppMastersCompanyProfileRoute,
  AppMastersGodownsRoute: AppMastersGodownsRoute,
  AppMastersItemsRoute: AppMastersItemsRoute,
  AppMastersPartiesRoute: AppMastersPartiesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DesignAccountingRouteChildren {
  DesignAccountingSidebarRoute: typeof DesignAccountingSidebarRoute
}

const DesignAccountingRouteChildren: DesignAccountingRouteChildren = {
  DesignAccountingSidebarRoute: DesignAccountingSidebarRoute,
}

const DesignAccountingRouteWithChildren =
  DesignAccountingRoute._addFileChildren(DesignAccountingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  DesignAccountingRoute: DesignAccountingRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
